spring:
  application:
    name: activityservice

  data:
    mongodb:
      uri: mongodb://username:password@localhost:27017/activitydb?authSource=admin
      database: aiactivityfitness

server:
  port: 8082